[package]
name = "ableton-git"
version = "0.2.0"
authors = ["Clinton Burgos <clintburgos@users.noreply.github.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
regex = "1.1.2"

[[bin]]
name = "ableton-git"
path = "src/main.rs"
